 
    Questions = ["if there are 445454 men,86592 women,300 girls in a country and The population of that country is 532934 then what is the number of boys in that country", "What is 1/6 of a year (in months)"];

    const random = Math.floor(Math.random() * Questions.length);
    console.log(Questions[random]);
    document.write("Q1 : ",Questions[random])

    function Next(){
        const random = Math.floor(Math.random() * Questions.length);
        console.log(Questions[random]);
        document.write("Q1 : ",Questions[random])
       
    }

    
  

 